# version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/next.Dockerfile
    environment:
      NEXT_PUBLIC_HOSTNAME: ${NEXT_PUBLIC_HOSTNAME}
      BACKEND_API_BASE: ${BACKEND_API_BASE}
      JWT_COOKIE_NAME : ${JWT_COOKIE_NAME}
    platform: linux/x86_64
    image: yyoooonn/aimlfront:latest
    ports:
      - 3000:3000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.Dockerfile
    # platform for ec2 environment
    platform: linux/x86_64
    image: yyoooonn/aimlfrontnginx:latest
    ports:
      - 80:80
    depends_on:
      - frontend
