# .github/workflows/docker-build-push.yml
name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: AIML_PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env
        run:
          echo "NEXT_PUBLIC_HOSTNAME=${{ vars.NEXT_PUBLIC_HOSTNAME }}" > .env |
          echo "DOCKER_REPO=${{ vars.DOCKER_AIML_USERNAME }}" >> .env
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_AIML_USERNAME }}
          password: ${{ secrets.DOCKER_AIML_ACCESS_TOKEN }}

      - name: Build containers
        run: docker compose -f docker-compose.yml build

      - name: Run containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services
        run: sleep 10

      - name: Check services
        run: docker compose ps -a

      - name: Stop containers
        run: docker compose down

      # Optional: Push images to Docker Hub
      - name: Push images to Docker Hub
        run: docker compose push
# name: Docker Image CI

# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: "Log level"
#         required: true
#         default: "warning"
#         type: choice
#         options:
#           - info
#           - warning
#           - debug

#   push:
#     branches: ["main"]
#     paths-ignore:
#       - ".github/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       NEXT_PUBLIC_HOSTNAME: ${{secrets.NEXT_PUBLIC_HOSTNAME}}
#       NEXT_PUBLIC_PORT: ${{secrets.NEXT_PUBLIC_PORT}}
#       NEXT_PUBLIC_SOCKET_HOST: ${{secrets.NEXT_PUBLIC_SOCKET_HOST}}
#       NEXT_PUBLIC_SOCKET_PORT: ${{secrets.NEXT_PUBLIC_SOCKET_PORT}}
#       BACKEND_API_ENDPOINT: ${{secrets.BACKEND_API_ENDPOINT}}
#       JWT_COOKIE_KEY: ${{secrets.JWT_COOKIE_KEY}}
#     steps:
#       - name: checkout
#         uses: actions/checkout@v4

#       - name: dockerlogin
#         uses: docker/login-action@v3
#         with:
#           username: ${{secrets.DOCKER_ID}}
#           password: ${{secrets.DOCKER_PASSWORD}}

#       - name: docker build & push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           file: ./docker/next.Dockerfile
#           build-args: |
#             NEXT_PUBLIC_HOSTNAME: ${{env.NEXT_PUBLIC_HOSTNAME}}
#             NEXT_PUBLIC_PORT: ${{env.NEXT_PUBLIC_PORT}}
#             NEXT_PUBLIC_SOCKET_HOST: ${{env.NEXT_PUBLIC_SOCKET_HOST}}
#             NEXT_PUBLIC_SOCKET_PORT: ${{env.NEXT_PUBLIC_SOCKET_PORT}}
#           tags: ${{secrets.DOCKER_REPO}}/aimlfront:latest
