name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_HOSTNAME: ${{secrets.NEXT_PUBLIC_HOSTNAME}}
      BACKEND_API_BASE: ${{secrets.BACKEND_API_BASE}}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: dockerlogin
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./docker/next.Dockerfile
        build-args: |
          NEXT_PUBLIC_HOSTNAME: ${{env.NEXT_PUBLIC_HOSTNAME}}
          BACKEND_API_BASE: ${{env.BACKEND_API_BASE}}
        tag: latest
