name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_HOSTNAME: ${{secrets.NEXT_PUBLIC_HOSTNAME}}
      BACKEND_API_BASE: ${{secrets.BACKEND_API_BASE}}

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image & push
      run: |
        # docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username foo --password-stdin
        docker build --build-arg NEXT_PUBLIC_HOSTNAME="${{env.NEXT_PUBLIC_HOSTNAME}}"\
        --build-arg BACKEND_API_BASE="${{env.BACKEND_API_BASE}}"\
        -t $DOCKER_ID/frontend . -f ./docker/next.Dockerfile
        docker push $DOCKER_ID/frontend:latest

    
