# .github/workflows/docker-build-push.yml
name: Docker Compose CI

on:
  pull_request:
    branches: [dev]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: AIML_PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_HOSTNAME=${{ vars.NEXT_PUBLIC_HOSTNAME }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build containers with Docker Compose
        run: docker-compose -f docker-compose.yml build

      # 예: 빌드 후 컨테이너 실행 및 테스트
      - name: Run services
        run: docker-compose -f docker-compose.yml up -d

      # Optional: Wait for services to be healthy
      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          sleep 30  # Adjust the sleep time as needed

      # add test if needed
      # - name: Run tests inside container (optional)
      #   run: docker-compose exec -T your-service-name npm test

      - name: Stop containers
        run: docker-compose down
